# Generated by Django 4.2.9 on 2024-01-05 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Non Binary'), (3, 'Prefer not to say')], default=3)),
                ('DOB', models.DateTimeField()),
                ('adr_street', models.CharField(max_length=100)),
                ('adr_city', models.CharField(max_length=50)),
                ('adr_zip', models.CharField(max_length=10)),
                ('adr_country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('DL_date', models.DateTimeField()),
                ('contactable', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stop_type', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('google_id', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('input_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.region')),
            ],
        ),
    ]
