# Generated by Django 4.2.9 on 2024-01-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='DOB',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Birthday'),
        ),
    ]
