# Generated by Django 4.2.9 on 2024-01-05 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purpose',
            name='date_created',
        ),
    ]
