# Generated by Django 4.2.9 on 2024-01-06 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_remove_purpose_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('type', models.IntegerField(choices=[(0, 'Sedan'), (1, 'SUV'), (2, 'Roadster'), (3, 'Minvan'), (4, 'Truck'), (5, 'Bus'), (6, 'LKW')], default=0)),
                ('year', models.CharField(max_length=4)),
                ('engine', models.IntegerField(choices=[(0, 'Gasoline'), (1, 'Diesel'), (2, 'Hybrid'), (3, 'Electric'), (4, 'LNG'), (5, 'OTHER')], default=0)),
                ('smoking', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('max_pax', models.IntegerField(default=1)),
                ('operator', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
