# Generated by Django 4.2.9 on 2024-01-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_customuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='google_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='stop_type',
            field=models.IntegerField(choices=[(0, 'Address'), (1, 'Bus Stop'), (2, 'Intersection'), (3, 'Parking Lot'), (4, 'Gas Station')], default=0),
        ),
    ]
