# Generated by Django 4.2.9 on 2024-01-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_hitch_request_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
