# Generated by Django 4.2.9 on 2024-01-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='operator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
