# Generated by Django 4.2.9 on 2024-01-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_location_google_id_alter_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='google_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
