# Generated by Django 4.2.9 on 2024-01-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='direction',
            field=models.BooleanField(choices=[(False, 'One Way'), (True, 'Return Trip')], default=False),
        ),
    ]
