# Generated by Django 4.2.9 on 2024-01-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_trip_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='smoking',
            field=models.IntegerField(choices=[(True, 'Yes'), (False, 'No')], default=0),
        ),
    ]
