# Generated by Django 4.2.9 on 2024-01-06 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_driver_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('trip_date', models.DateField()),
                ('trip_status', models.IntegerField(choices=[(0, 'Confirmed'), (1, 'Completed'), (2, 'Cancelled')], default=0)),
                ('max_hitch', models.IntegerField(default=0)),
                ('depart_time', models.TimeField()),
                ('expected_duration', models.DurationField(blank=True, null=True)),
                ('expected_arrival_time', models.TimeField(blank=True, null=True)),
                ('depart_window', models.DurationField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=150, null=True)),
                ('direction', models.IntegerField(choices=[(0, 'One Way'), (1, 'Return Trip')], default=0)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('recurring', models.IntegerField(blank=True, null=True)),
                ('mon', models.BooleanField(default=False)),
                ('tue', models.BooleanField(default=False)),
                ('wed', models.BooleanField(default=False)),
                ('thu', models.BooleanField(default=False)),
                ('fri', models.BooleanField(default=False)),
                ('sat', models.BooleanField(default=False)),
                ('sun', models.BooleanField(default=False)),
                ('suggested_tip', models.FloatField(blank=True, null=True)),
                ('pickup_radius', models.IntegerField(default=2)),
                ('max_detour_dist', models.IntegerField(default=5)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='rides.location')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.location')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.purpose')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.region')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.vehicle')),
            ],
            options={
                'ordering': ['-trip_date'],
            },
        ),
    ]
