# Generated by Django 4.2.9 on 2024-01-13 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_alter_message_options_alter_trip_recurring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adr_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='adr_country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='adr_street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='adr_zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ZIP Code'),
        ),
        migrations.AlterField(
            model_name='request',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_depart', to='rides.location'),
        ),
        migrations.AlterField(
            model_name='request',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.location'),
        ),
        migrations.AlterField(
            model_name='request',
            name='hitcher',
            field=models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='purpose',
            field=models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='rides.purpose'),
        ),
        migrations.AlterField(
            model_name='request',
            name='trip_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='depart',
            field=models.ForeignKey(default='no record', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='depart', to='rides.location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(default='no record', on_delete=django.db.models.deletion.SET_DEFAULT, to='rides.location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='purpose',
            field=models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='rides.purpose'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='operator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Operated by'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
