# Generated by Django 4.2.9 on 2024-01-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_message_was_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
    ]
