# Generated by Django 4.2.9 on 2024-01-13 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_alter_customuser_adr_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='hitcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
