# Generated by Django 4.2.9 on 2024-01-13 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_alter_vehicle_make_alter_vehicle_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='input_by',
            field=models.ForeignKey(default='no record', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_depart', to='rides.location'),
        ),
        migrations.AlterField(
            model_name='request',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.location'),
        ),
        migrations.AlterField(
            model_name='request',
            name='hitcher',
            field=models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='purpose',
            field=models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='rides.purpose'),
        ),
        migrations.AlterField(
            model_name='request',
            name='trip_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='depart',
            field=models.ForeignKey(default='no record', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='depart', to='rides.location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(default='no record', on_delete=django.db.models.deletion.SET_DEFAULT, to='rides.location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(default='no driver info', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='purpose',
            field=models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='rides.purpose'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(default='no vehicle record', on_delete=django.db.models.deletion.SET_DEFAULT, to='rides.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(default='no record', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
