# Generated by Django 4.2.9 on 2024-01-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_alter_request_hitcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Not Active'), (2, 'Deleted')], default=0),
        ),
    ]
