# Generated by Django 4.2.9 on 2024-01-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0014_customuser_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='recurring',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=0),
        ),
    ]
