# Generated by Django 3.2.13 on 2024-01-24 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_alter_trip_recurring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hitch_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('depart_date', models.DateField()),
                ('depart_time', models.TimeField(blank=True, null=True)),
                ('depart_window', models.DurationField(blank=True, null=True)),
                ('smoking', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('direction', models.IntegerField(choices=[(0, 'One Way'), (1, 'Return Trip')], default=0)),
                ('recurring', models.IntegerField(blank=True, null=True)),
                ('pax_approved', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('trip_rating', models.IntegerField(blank=True, null=True)),
                ('trip_comment', models.CharField(blank=True, max_length=50, null=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-depart_date'],
            },
        ),
        migrations.CreateModel(
            name='Stop_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=50, unique=True)),
                ('stop_icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('rating_type', models.CharField(choices=[('driver', 'Driver'), ('hitcher', 'Hitcher')], max_length=7)),
                ('star_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='request',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='request',
            name='hitcher',
        ),
        migrations.RemoveField(
            model_name='request',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='request',
            name='region',
        ),
        migrations.RemoveField(
            model_name='request',
            name='trip_id',
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-depart_date']},
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_date',
            new_name='depart_date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='stop_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.AddField(
            model_name='customuser',
            name='average_driver_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='average_hitcher_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='was_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='direction',
            field=models.BooleanField(choices=[(0, 'One Way'), (1, 'Return Trip')], default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='max_detour_dist',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='max_hitch',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_radius',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Confirmed'), (1, 'Completed'), (2, 'Cancelled')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='smoking',
            field=models.IntegerField(choices=[(True, 'Yes'), (False, 'No')], default=0),
        ),
        migrations.DeleteModel(
            name='Driver_rating',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AddField(
            model_name='user_rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hitch_request',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_depart', to='rides.location'),
        ),
        migrations.AddField(
            model_name='hitch_request',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.location'),
        ),
        migrations.AddField(
            model_name='hitch_request',
            name='hitcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hitch_request',
            name='purpose',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rides.purpose'),
        ),
        migrations.AddField(
            model_name='hitch_request',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.region'),
        ),
        migrations.AddField(
            model_name='hitch_request',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hitch_requests', to='rides.trip'),
        ),
        migrations.AddField(
            model_name='location',
            name='stoptype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rides.stop_type'),
        ),
    ]
