# Generated by Django 3.2.13 on 2024-01-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0016_auto_20240124_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='direction',
            field=models.IntegerField(choices=[(0, 'One Way'), (1, 'Return Trip')], default=0),
        ),
    ]
