# Generated by Django 4.2.9 on 2024-01-18 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0016_alter_request_depart_date_alter_request_depart_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hitch_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('depart_date', models.DateField()),
                ('depart_time', models.TimeField(blank=True, null=True)),
                ('depart_window', models.DurationField(blank=True, null=True)),
                ('smoking', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('direction', models.IntegerField(choices=[(0, 'One Way'), (1, 'Return Trip')], default=0)),
                ('recurring', models.IntegerField(blank=True, null=True)),
                ('pax_approved', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('trip_rating', models.IntegerField(blank=True, null=True)),
                ('trip_comment', models.CharField(blank=True, max_length=50, null=True)),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_depart', to='rides.location')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.location')),
                ('hitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purpose', models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='rides.purpose')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.region')),
                ('trip_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.trip')),
            ],
            options={
                'ordering': ['-depart_date'],
            },
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
