# Generated by Django 4.2.9 on 2024-01-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0017_hitch_request_delete_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hitch_request',
            old_name='trip_id',
            new_name='trip',
        ),
    ]
