# Generated by Django 3.2.13 on 2024-01-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0017_alter_trip_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='direction',
            field=models.BooleanField(choices=[(0, 'One Way'), (1, 'Return Trip')], default=False),
        ),
    ]
