# Generated by Django 4.2.9 on 2024-01-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_rename_trip_id_hitch_request_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitch_request',
            name='purpose',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rides.purpose'),
        ),
    ]
