# Generated by Django 3.2.13 on 2024-01-25 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_alter_trip_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitch_request',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hitch_requests', to='rides.trip'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
