# Generated by Django 4.2.9 on 2024-01-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0019_alter_hitch_request_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-depart_date']},
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_date',
            new_name='depart_date',
        ),
    ]
