# Generated by Django 3.2.13 on 2024-01-25 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0020_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitch_request',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='hitch_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.hitch_request'),
        ),
        migrations.AlterField(
            model_name='message',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.trip'),
        ),
        migrations.AlterField(
            model_name='region',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.customuser'),
        ),
        migrations.AlterField(
            model_name='user_rating',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
