# Generated by Django 4.2.9 on 2024-01-19 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0021_stop_type_remove_location_stop_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('rating_type', models.CharField(choices=[('driver', 'Driver'), ('hitcher', 'Hitcher')], max_length=7)),
                ('star_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='average_driver_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='average_hitcher_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
        migrations.DeleteModel(
            name='Driver_rating',
        ),
        migrations.AddField(
            model_name='user_rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
