# Generated by Django 4.2.9 on 2024-01-19 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0022_user_rating_customuser_average_driver_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitch_request',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hitch_requests', to='rides.trip'),
        ),
    ]
