# Generated by Django 3.2.13 on 2024-01-26 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0022_auto_20240125_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='depart',
            field=models.ForeignKey(blank=True, default='no record', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='depart', to='rides.location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(blank=True, default='no record', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rides.location'),
        ),
    ]
