# Generated by Django 4.2.9 on 2024-01-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0023_alter_hitch_request_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitch_request',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
