# Generated by Django 3.2.13 on 2024-01-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0024_auto_20240128_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='max_hitch',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='max_pax',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
