# Generated by Django 4.2.9 on 2024-01-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0024_hitch_request_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='max_detour_dist',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='max_hitch',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_radius',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
