# Generated by Django 4.2.9 on 2024-01-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0025_alter_trip_max_detour_dist_alter_trip_max_hitch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Confirmed'), (1, 'Completed'), (2, 'Cancelled')], default=0, null=True),
        ),
    ]
